### ISSUE TITLE
Shrink image size to improve performance

### ISSUE THREAD

**Issue by andrewjkerr** [swamphacks/2018-Preregistration#5]
Hi! I really love the look of the new pre-registration site; great job!

One thing that I noticed is that all of the images take ~7sec to load:
![image](https://user-images.githubusercontent.com/1739462/28288272-b2006e6a-6b0c-11e7-9e73-c17d96d7f656.png)

Is there any way y'all could shrink/compress the images in order to make them load a bit faster?
 This should also help the performance of the site as well. :)

Thanks!

### Reproduction Steps

1. Open the Chrome inspector and click on the "Performance" tab
2. Start recording by clicking on the "record" icon in the top left of the Performance tool
3. Hard-reload the page (cmd + shift + R)
4. Click "stop"
5. Expand the "Network" tab inside of the Performance tool
6. Scroll down a little bit to see the images on the timeline

**Comment by zhangcandrew** [comment]
Hey Andrew! Thanks so much for letting us know about that! I've been coding with cached versions of the site and totally forgot to do a hard reload. 

7 seconds is definitely harsh for a webpage, I'll compress the images down.

**Comment by andrewjkerr** [comment]
![image](https://user-images.githubusercontent.com/1739462/28450013-80399a5c-6db2-11e7-87fc-ec0f09a542ed.png)

Woo, this is much better! Thanks for the quick response and update! 🎉 

Going to close this out now. :)
